#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

if [[ -z "$DGD" ]]; then
    DGD=$(dappCreate dss-deploy DGD "$(seth --to-uint256 "$(seth --to-wei 1000000 ETH)")")
    log "DGD=$DGD"
    export DGD
fi

# shellcheck source=libexec/dss/deploy-ilk
. "$LIBEXEC_DIR/dss/deploy-ilk" "DGD" "${1:-"A"}" "GemJoin3" 9
