#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

if [[ -z "$REP" ]]; then
    REP=$(dappCreate dss-deploy REP "$(seth --to-uint256 "$(seth --to-wei 1000000 ETH)")")
    log "REP=$REP"
    export REP
fi

# shellcheck source=libexec/dss/deploy-ilk
. "$LIBEXEC_DIR/dss/deploy-ilk" "REP" "${1:-"A"}" "GemJoin"
