#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

if [[ -z "$GNT" ]]; then
    GNT=$(dappCreate dss-deploy GNT "$(seth --to-uint256 "$(seth --to-wei 1000000 ETH)")")
    log "GNT=$GNT"
    export GNT
fi

# shellcheck source=libexec/dss/deploy-ilk
. "$LIBEXEC_DIR/dss/deploy-ilk" "GNT" "${1:-"A"}" "GemJoin4"
