#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

if [[ -z "$BAT" ]]; then
    BAT=$(dappCreate dss-deploy BAT "$(seth --to-uint256 "$(seth --to-wei 1000000 ETH)")")
    log "BAT=$BAT"
    export BAT
fi

# shellcheck source=libexec/dss/deploy-ilk
. "$LIBEXEC_DIR/dss/deploy-ilk" "BAT" "${1:-"A"}" "GemJoin"
