#!/usr/bin/env bash

# shellcheck source=bin/lib/common.sh
. "$LIB_DIR/common.sh"

if [[ -z "$SAI" ]]; then
    SAI=$(dappCreate dss-deploy DSToken "$(seth --to-bytes32 "$(seth --from-ascii "SAI")")")
    log "SAI=$SAI"
    export SAI
fi

# shellcheck source=/dev/null
source "$LIBEXEC_DIR/dss/deploy-ilk" "SAI" "" "AuthGemJoin"
