#!/usr/bin/env bash
set -ex

export ETH_GAS=${ETH_GAS:-"7000000"}

# Get config variables
CONFIG_FILE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/out/config.json"

delay=$(jq -r ".pauseDelay" "$CONFIG_FILE")

if [ "$delay" -gt 0 ]; then
    # shellcheck source=/dev/null
    . load-addresses

    cd contracts/testchain-pause-proxy-actions
    dapp build
    action=$(dapp create ActionChangeDelay)
    calldata="$(seth calldata 'changeDelay(address,address,uint256)' "$MCD_PAUSE" "$action" "$(seth --to-uint256 "$delay")")"
    seth send "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
fi