#!/usr/bin/env bash
set -ex

export ETH_GAS=${ETH_GAS:-"7000000"}

# Get config variables
CONFIG_FILE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/out/config.json"

# shellcheck source=/dev/null
. load-addresses

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    seth send "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$MCD_SPOT"
done

echo "SET ILKS PIP WHITELIST COMPLETED SUCCESSFULLY"
