#!/usr/bin/env bash
set -ex

export ETH_GAS=${ETH_GAS:-"7000000"}

export CONFIG_STEP=${CONFIG_STEP:-"step-3"}

# shellcheck source=/dev/null
./step-1-deploy

# shellcheck source=/dev/null
./poll-deploy

# shellcheck source=/dev/null
./scripts/set-ilks-spell-line

if [ "$CONFIG_STEP" = "step-3" ]; then
    # shellcheck source=/dev/null
    ./scripts/set-pause-delay
fi

echo "STEP 3 COMPLETED SUCCESSFULLY"
