#!/usr/bin/env bash

export CONFIG_STEP=${CONFIG_STEP:-"step-2"}
# shellcheck source=lib/common.sh
. "${LIB_DIR:-$(cd "${0%/*}/lib"&&pwd)}/common.sh" "step-2"

"$BIN_DIR"/step-1-deploy

"$BIN_DIR"/poll-deploy

if [ "$CONFIG_STEP" = "step-2" ]; then
    "$LIBEXEC_DIR"/set-pause-delay
fi

echo "STEP 2 COMPLETED SUCCESSFULLY"
