#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "${LIB_DIR:-$(cd "${0%/*}/lib"&&pwd)}/common.sh"
CONFIG_STEP=$(setConfigStep "step-3")
export CONFIG_STEP

"$BIN_DIR"/step-1-deploy

"$BIN_DIR"/poll-deploy

"$LIBEXEC_DIR"/set-ilks-spell-line

if [[ "$CONFIG_STEP" == "step-3" ]]; then
    "$LIBEXEC_DIR"/set-pause-delay
fi

echo "STEP 3 COMPLETED SUCCESSFULLY"
