#!/usr/bin/env bash
set -ex

export ETH_GAS=${ETH_GAS:-"7000000"}

export CONFIG_STEP=${CONFIG_STEP:-"step-4"}
CONFIG_FILE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/$CONFIG_STEP.json"

# shellcheck source=/dev/null
./step-1-deploy

# shellcheck source=/dev/null
. load-addresses

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    # If it is a value set the price
    type=$(jq -r ".tokens.${token} | .pip | .type" "$CONFIG_FILE")
    if [ "${type}" = "value" ]; then
        price=$(jq -r ".tokens.${token} | .pip | .price" "$CONFIG_FILE")
        ./update-price "$token" "$price"
    fi

    ilks=$(jq -r ".tokens.${token}.ilks | keys_unsorted[]" "$CONFIG_FILE")
    for ilk in $ilks; do
        # Set Collateral debt ceiling
        line=$(jq -r ".tokens.${token}.ilks.${ilk} | .line" "$CONFIG_FILE")
        line=$(seth --to-uint256 "$(echo "$line"*10^45 | bc)")
        seth send "$MCD_MOM" 'execute(address,bytes memory)' "$MCD_MOM_LIB" "$(seth calldata 'file(address,bytes32,bytes32,uint256)' "$MCD_VAT" "$(seth --to-bytes32 "$(seth --from-ascii "${token}-${ilk}")")" "$(seth --to-bytes32 "$(seth --from-ascii "line")")" "$line")"
        # Set Collateral liquidation ratio
        mat=$(jq -r ".tokens.${token}.ilks.${ilk} | .mat" "$CONFIG_FILE")
        mat="$(seth --to-uint256 "$(echo "$mat * 10^25" | bc -l)" ETH)"
        seth send "$MCD_MOM" 'execute(address,bytes memory)' "$MCD_MOM_LIB" "$(seth calldata 'file(address,bytes32,bytes32,uint256)' "$MCD_SPOT" "$(seth --to-bytes32 "$(seth --from-ascii "${token}-${ilk}")")" "$(seth --to-bytes32 "$(seth --from-ascii "mat")")" "$mat")"
        # Set Collateral stability fee
        tax=$(jq -r ".tokens.${token}.ilks.${ilk} | .tax" "$CONFIG_FILE")
        tax=$(bc -l <<< "scale=27; e( l(${tax} / 100 + 1)/(60 * 60 * 24 * 365)) * 10^27")
        tax=$(seth --to-uint256 "${tax%.*}")
        seth send "$MCD_MOM" 'execute(address,bytes memory)' "$MCD_MOM_LIB" "$(seth calldata 'file(address,bytes32,bytes32,uint256)' "$MCD_JUG" "$(seth --to-bytes32 "$(seth --from-ascii "${token}-${ilk}")")" "$(seth --to-bytes32 "$(seth --from-ascii "tax")")" "$tax")"
        # Poke Spotter
        seth send "$MCD_SPOT" 'poke(bytes32)' "$(seth --to-bytes32 "$(seth --from-ascii "${token}-${ilk}")")"
    done
done

echo "STEP 4 COMPLETED SUCCESSFULLY"
