#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "${LIB_DIR:-$(cd "${0%/*}/lib"&&pwd)}/common.sh"
CONFIG_STEP=$(setConfigStep "step-4")
export CONFIG_STEP

"$BIN_DIR"/step-1-deploy

loadAddresses

"$LIBEXEC_DIR"/set-ilks-mat

"$LIBEXEC_DIR"/set-ilks-line

"$LIBEXEC_DIR"/set-ilks-duty

"$LIBEXEC_DIR"/set-ilks-price

"$LIBEXEC_DIR"/set-ilks-spotter-poke

"$LIBEXEC_DIR"/set-ilks-chop

"$LIBEXEC_DIR"/set-ilks-lump

"$LIBEXEC_DIR"/set-ilks-beg

"$LIBEXEC_DIR"/set-ilks-ttl

"$LIBEXEC_DIR"/set-ilks-tau

if [[ "$CONFIG_STEP" == "step-4" ]]; then
    "$LIBEXEC_DIR"/set-pause-auth-delay
    echo "STEP 4 COMPLETED SUCCESSFULLY"
fi
