#!/usr/bin/env bash
set -ex

export ETH_GAS=${ETH_GAS:-"7000000"}

export CONFIG_STEP=${CONFIG_STEP:-"step-4"}

# shellcheck source=/dev/null
./step-1-deploy

# shellcheck source=/dev/null
. scripts/load-addresses

# shellcheck source=/dev/null
./scripts/set-ilks-mat

# shellcheck source=/dev/null
./scripts/set-ilks-line

# shellcheck source=/dev/null
./scripts/set-ilks-duty

# shellcheck source=/dev/null
./scripts/set-ilks-price

# shellcheck source=/dev/null
./scripts/set-ilks-spotter-poke

if [ "$CONFIG_STEP" = "step-4" ]; then
    # shellcheck source=/dev/null
    ./scripts/set-pause-delay
fi

echo "STEP 4 COMPLETED SUCCESSFULLY"
