#!/usr/bin/env bash
set -ex

export CONFIG_STEP=${CONFIG_STEP:-"step-2"}

# shellcheck source=/dev/null
./step-1-deploy

# shellcheck source=/dev/null
./poll-deploy

echo "STEP 2 COMPLETED SUCCESSFULLY"
