#!/usr/bin/env bash
set -ex

export ETH_GAS=${ETH_GAS:-"7000000"}

export CONFIG_STEP=${CONFIG_STEP:-"step-3"}

# shellcheck source=/dev/null
./step-1-deploy

# shellcheck source=/dev/null
./set-ilks-spell-line

echo "STEP 3 COMPLETED SUCCESSFULLY"
