#!/usr/bin/env bash
set -ex

OSM="$(jq <"./out/addresses.json" -r ".PIP_${1}")"
VALUE="$(jq <"./out/addresses.json" -r ".VAL_${1}")"
SPOTTER="$(jq <"./out/addresses.json" -r ".MCD_SPOT")"

# Set DSValue price
seth send "$VALUE" 'poke(bytes32)' "$(seth --to-uint256 "$(seth --to-wei "$2" ETH)")"

if [ "$OSM" != "$VALUE" ]; then
    # Poke OSM
    seth send "$OSM" 'poke()'
fi

# Poke Spotter
seth send "$SPOTTER" 'poke(bytes32)' "$(seth --to-bytes32 "$(seth --from-ascii "$1")")"
