#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "${LIB_DIR:-$(cd "${0%/*}/../lib"&&pwd)}/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    seth send "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$MCD_SPOT"
done

echo "SET ILKS PIP WHITELIST COMPLETED SUCCESSFULLY"
