#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

log "SET POT DSR:"

# Set general debt ceiling (if defined)
dsr=$(jq -r ".pot_dsr | values" "$CONFIG_FILE")
if [[ "$dsr" != "" ]]; then
    dsr=$(bc -l <<< "scale=27; e( l(${dsr} / 100 + 1)/(60 * 60 * 24 * 365)) * 10^27")
    dsr=$(seth --to-uint256 "${dsr%.*}")
    calldata="$(seth calldata 'dripAndFile(address,address,address,bytes32,uint256)' "$MCD_PAUSE" "$MCD_GOV_ACTIONS" "$MCD_POT" "$(seth --to-bytes32 "$(seth --from-ascii "dsr")")" "$dsr")"
    sethSend "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
fi
