#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "${LIB_DIR:-$(cd "${0%/*}/../lib"&&pwd)}/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

{ test "$1" != "flap" && test "$1" != "flop"; } && exit 1

# Set ttl
ttl=$(jq -r ".$1_ttl | values" "$CONFIG_FILE")
if [[ "$ttl" != "" ]]; then
    calldata="$(seth calldata 'file(address,address,address,bytes32,uint256)' "$MCD_PAUSE" "$MCD_GOV_ACTIONS" "$(eval echo "\$MCD_$(echo "$1" | tr '[:lower:]' '[:upper:]')")" "$(seth --to-bytes32 "$(seth --from-ascii "ttl")")" "$ttl")"
    seth send "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
fi

echo "SET $(echo "$1" | tr '[:lower:]' '[:upper:]') TTL COMPLETED SUCCESSFULLY"
