#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

log "SET ILKS LINE:"

setLine() {
    if [[ "$2" != "" && "$2" != "0" ]]; then
        local line
        line=$(echo "$2"*10^45 | bc)
        line=$(seth --to-uint256 "${line%.*}")
        calldata="$(seth calldata 'file(address,address,address,bytes32,bytes32,uint256)' "$MCD_PAUSE" "$MCD_GOV_ACTIONS" "$MCD_VAT" "$(seth --to-bytes32 "$(seth --from-ascii "$1")")" "$(seth --to-bytes32 "$(seth --from-ascii "line")")" "$line")"
        sethSend "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
    fi
}

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")

for token in $tokens; do
    ilks=$(jq -r ".tokens.${token}.ilks | keys_unsorted[]" "$CONFIG_FILE")
    for ilk in $ilks; do
        setLine "${token}-${ilk}" "$(jq -r ".tokens.${token}.ilks.${ilk} | .line" "$CONFIG_FILE")"
    done
done

if [[ -n "$MIGRATION" ]]; then
    setLine "SAI" "$(jq -r ".migration | .line" "$CONFIG_FILE")"
fi
