#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

log "SET ILKS OSM:"

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    pipAddr=$(jq -r ".tokens.${token} | .import.pip | values" "$CONFIG_FILE")
    if [[ "$pipAddr" == "" ]]; then
        osmDelay=$(jq -r ".tokens.${token} | .pipDeploy | .osmDelay" "$CONFIG_FILE")
        if [[ "$osmDelay" -gt 0 ]]; then
            # Deploy OSM
            contract=$(dappCreate osm OSM "$(eval echo "\$VAL_${token}")")
            eval "export PIP_${token}=${contract}"
            log "PIP_${token}=$(eval "echo ${contract}")"
            # Set OSM delay
            sethSend "$(eval echo "\$PIP_${token}")" 'step(uint16)' "$osmDelay"
            # Whitelist OSM in Medianizer (skip if source is DSValue)
            type=$(jq -r ".tokens.${token} | .pipDeploy | .type | values" "$CONFIG_FILE")
            [[ "$type" == "median" ]] && sethSend "$(eval echo "\$VAL_${token}")" 'kiss(address)' "$(eval echo "\$PIP_${token}")"
            # Whithelist Spotter in OSM
            sethSend "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$MCD_SPOT"
            # Whithelist End in OSM
            sethSend "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$MCD_END"
            # Set osm in spotter ilks
            ilks=$(jq -r ".tokens.${token}.ilks | keys_unsorted[]" "$CONFIG_FILE")
            for ilk in $ilks; do
                calldata="$(seth calldata 'file(address,address,address,bytes32,bytes32,address)' "$MCD_PAUSE" "$MCD_GOV_ACTIONS" "$MCD_SPOT" "$(seth --to-bytes32 "$(seth --from-ascii "${token}-${ilk}")")" "$(seth --to-bytes32 "$(seth --from-ascii "pip")")" "$(eval echo "\$PIP_${token}")")"
                sethSend "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
            done
        fi
    fi
done

for token in $tokens; do
addAddresses <<EOF
{
    "PIP_${token}": "$(eval echo "\$PIP_${token}")"
}
EOF
done
