#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

log "SET VOW BUMP:"

# Set general debt ceiling (if defined)
bump=$(jq -r ".vow_bump | values" "$CONFIG_FILE")
if [[ "$bump" != "" ]]; then
    bump=$(echo "$bump"*10^45 | bc)
    bump=$(seth --to-uint256 "${bump%.*}")
    calldata="$(seth calldata 'file(address,address,address,bytes32,uint256)' "$MCD_PAUSE" "$MCD_GOV_ACTIONS" "$MCD_VOW" "$(seth --to-bytes32 "$(seth --from-ascii "bump")")" "$bump")"
    sethSend "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
fi
