#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

log "SET VOW HUMP:"

# Set general debt ceiling (if defined)
hump=$(jq -r ".vow_hump | values" "$CONFIG_FILE")
if [[ "$hump" != "" ]]; then
    hump=$(echo "$hump"*10^45 | bc)
    hump=$(seth --to-uint256 "${hump%.*}")
    calldata="$(seth calldata 'file(address,address,address,bytes32,uint256)' "$MCD_PAUSE" "$MCD_GOV_ACTIONS" "$MCD_VOW" "$(seth --to-bytes32 "$(seth --from-ascii "hump")")" "$hump")"
    sethSend "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
fi
