#!/usr/bin/env bash

# shellcheck source=bin/lib/common.sh
. "$LIB_DIR/common.sh"

export ETH_FROM=${ETH_FROM:-$(seth rpc eth_coinbase)}

test -z "$BAT" && BAT=$(dappCreate dss-deploy BAT "$(seth --to-uint256 "$(seth --to-wei 1000000 ETH)")")
log "BAT=$BAT"
export BAT

# shellcheck source=/dev/null
source "$LIBEXEC_DIR/dss/deploy-ilk" "BAT" "${1:-"A"}" "GemJoin"
