#!/usr/bin/env bash

# shellcheck source=bin/lib/common.sh
. "$LIB_DIR/common.sh"

if [[ -z "$ETH" ]]; then
    ETH=$(dappCreate dss-deploy WETH9_)
    log "ETH=$ETH"
    export ETH
fi

# shellcheck source=/dev/null
source "$LIBEXEC_DIR/dss/deploy-ilk" "ETH" "${1:-"A"}" "GemJoin"
