#!/usr/bin/env bash

# shellcheck source=bin/lib/common.sh
. "$LIB_DIR/common.sh"

export ETH_FROM=${ETH_FROM:-$(seth rpc eth_coinbase)}

test -z "$GNT" && GNT=$(dappCreate dss-deploy GNT "$(seth --to-uint256 "$(seth --to-wei 1000000 ETH)")")
log "GNT=$GNT"
export GNT

# shellcheck source=/dev/null
source "$LIBEXEC_DIR/dss/deploy-ilk" "GNT" "${1:-"A"}" "GemJoin4"
