#!/usr/bin/env bash

# shellcheck source=bin/lib/common.sh
. "$LIB_DIR/common.sh"

export ETH_FROM=${ETH_FROM:-$(seth rpc eth_coinbase)}

test -z "$ETH" && ETH=$(dappCreate dss-deploy WETH9_)
log "ETH=$ETH"
export ETH

# shellcheck source=/dev/null
source "$LIBEXEC_DIR/dss/deploy-ilk" "ETH" "${1:-"A"}" "GemJoin"
