#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "${LIB_DIR:-$(cd "${0%/*}/../lib"&&pwd)}/common.sh"

loadAddresses

type=$(jq -r ".tokens.${1} | .pip | .type" "$OUT_DIR/config.json")
if [ "$type" == "value" ]; then
    # Set DSValue price
    eval seth send "\$VAL_${1} 'poke(bytes32)' $(seth --to-uint256 "$(seth --to-wei "$2" ETH)")"
fi

if [ "$(eval echo "\$PIP_${1}")" != "$(eval echo "\$VAL_${1}")" ]; then
    # Poke OSM
    seth send "$(eval echo "\$PIP_${1}")" 'poke()'
fi
