#!/usr/bin/env bash

. ${LIB_DIR:-$(cd "${0%/*}/../lib"&&pwd)}/common.sh

# Get config variables
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
CONFIG_FILE="$OUT_DIR/config.json"

delay=$(jq -r ".pauseDelay" "$CONFIG_FILE")

if [ "$delay" -gt 0 ]; then
    loadAddresses

    cd contracts/testchain-pause-proxy-actions
    dapp build
    action=$(dapp create ActionChangeDelay)
    calldata="$(seth calldata 'changeDelay(address,address,uint256)' "$MCD_PAUSE" "$action" "$(seth --to-uint256 "$delay")")"
    seth send "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
fi