#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "${LIB_DIR:-$(cd "${0%/*}/../lib"&&pwd)}/common.sh"

CONFIG_FILE="$OUT_DIR/config.json"
loadAddresses

cd contracts/line-spell
dapp build

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    ilks=$(jq -r ".tokens.${token}.ilks | keys_unsorted[]" "$CONFIG_FILE")
    for ilk in $ilks; do
        ilksT+="$(seth --to-bytes32 "$(seth --from-ascii "${token}-${ilk}")"),"
        lines+="$(seth --to-uint256 "$(bc <<< "$(jq -r ".tokens.${token}.ilks.${ilk} | .line" "$CONFIG_FILE")*10^45")"),"
    done
done

ilksT="[${ilksT%,}]"
lines="[${lines%,}]"

EXEC_PROPOSAL=$(seth send --create out/MultiLineSpell.bin 'MultiLineSpell(address,address,address,bytes32[] memory,uint256[] memory)' "$MCD_PAUSE" "$MCD_PAUSE_PLAN" "$MCD_VAT" "$ilksT" "$lines")

cd ../../

# Add new addresses to json file
addAddresses <<EOF
{
    "EXEC_PROPOSAL": "$EXEC_PROPOSAL"
}
EOF

echo "EXECUTIVE SPELL DEBT CEILINGS COMPLETED SUCCESSFULLY"
