#!/usr/bin/env bash
set -ex

export ETH_GAS=${ETH_GAS:-"7000000"}

# Get config variables
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
CONFIG_FILE="$DIR/../out/config.json"

# shellcheck source=/dev/null
. "$DIR/load-addresses"

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    # If it is a value set the price
    type=$(jq -r ".tokens.${token} | .pip | .type" "$CONFIG_FILE")
    if [ "${type}" = "value" ]; then
        price=$(jq -r ".tokens.${token} | .pip | .price" "$CONFIG_FILE")
        "$DIR/set-price" "$token" "$price"
    fi
done

echo "SET ILKS PRICE COMPLETED SUCCESSFULLY"
