#!/usr/bin/env bash

. ${LIB_DIR:-$(cd "${0%/*}/../lib"&&pwd)}/common.sh

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"

loadAddresses

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    ilks=$(jq -r ".tokens.${token}.ilks | keys_unsorted[]" "$CONFIG_FILE")
    for ilk in $ilks; do
        seth send "$MCD_SPOT" 'poke(bytes32)' "$(seth --to-bytes32 "$(seth --from-ascii "${token}-${ilk}")")"
    done
done

echo "SET SPOTTER POKE COMPLETED SUCCESSFULLY"
