#!/usr/bin/env bash
. ${LIB_DIR:-$(cd "${0%/*}/../lib"&&pwd)}/common.sh

CONFIG_FILE="$OUT_DIR/config.json"
loadAddresses

# Set general debt ceiling (if defined)
wait=$(jq -r ".wait | values" "$CONFIG_FILE")
if [ "$wait" != "" ]; then
    calldata="$(seth calldata 'file(address,address,address,bytes32,uint256)' "$MCD_PAUSE" "$MCD_PAUSE_PLAN" "$MCD_VOW" "$(seth --to-bytes32 "$(seth --from-ascii "wait")")" "$wait")"
    seth send "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
fi

echo "SET WAIT COMPLETED SUCCESSFULLY"
