#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "${LIB_DIR:-$(cd "${0%/*}/../lib"&&pwd)}/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    addr=$(jq -r ".tokens.${token} | .pip | .addr | values" "$CONFIG_FILE")
    type=$(jq -r ".tokens.${token} | .pip | .type | values" "$CONFIG_FILE")
    if [[ "$addr" != "" || "$type" == "median" ]]; then
        # Whitelist Spotter in OSM or in Median
        sethSend "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$MCD_SPOT"
    fi
done

log "SET ILKS PIP WHITELIST COMPLETED SUCCESSFULLY"
