#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "${LIB_DIR:-$(cd "${0%/*}/../lib"&&pwd)}/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"

delay=$(jq -r ".pauseDelay" "$CONFIG_FILE")

if [ "$delay" -gt 0 ]; then
    loadAddresses

    cd "$DAPP_LIB/testchain-pause-proxy-actions"
    dapp build
    action=$(dapp create ActionChangeDelay)
    calldata="$(seth calldata 'changeDelay(address,address,uint256)' "$MCD_PAUSE" "$action" "$(seth --to-uint256 "$delay")")"
    seth send "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
fi
