#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "${LIB_DIR:-$(cd "${0%/*}/../lib"&&pwd)}/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    # If it is a value set the price
    type=$(jq -r ".tokens.${token} | .pip | .type" "$CONFIG_FILE")
    if [[ "$type" == "value" ]]; then
        price=$(jq -r ".tokens.${token} | .pip | .price" "$CONFIG_FILE")
        "$LIBEXEC_DIR/set-price" "$token" "$price"
    fi
done

echo "SET ILKS PRICE COMPLETED SUCCESSFULLY"
