#!/usr/bin/env bash
set -ex

export ETH_GAS=${ETH_GAS:-"7000000"}

# Get config variables
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
CONFIG_FILE="$DIR/../out/config.json"

# shellcheck source=/dev/null
. "$DIR/load-addresses"

# Set general debt ceiling (if defined)
bump=$(jq -r ".bump" "$CONFIG_FILE")
if [ "$bump" != "" ]; then
    bump=$(echo "$bump"*10^45 | bc)
    bump=$(seth --to-uint256 "${bump%.*}")
    calldata="$(seth calldata 'file(address,address,address,bytes32,uint256)' "$MCD_PAUSE" "$MCD_PAUSE_PLAN" "$MCD_VOW" "$(seth --to-bytes32 "$(seth --from-ascii "bump")")" "$bump")"
    seth send "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
fi

echo "SET BUMP COMPLETED SUCCESSFULLY"
