#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "${LIB_DIR:-$(cd "${0%/*}/../lib"&&pwd)}/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    pipAddr=$(jq -r ".tokens.${token} | .pip | values" "$CONFIG_FILE")
    type=$(jq -r ".tokens.${token} | .pipDeploy | .type | values" "$CONFIG_FILE")
    if [[ "$pipAddr" != "" || "$type" == "median" ]]; then
        # Whitelist Spotter in OSM or in Median only if DEPLOYER has permission to do it
        if [[ "$(seth call "$(eval echo "\$PIP_${token}")" 'wards(address)(uint256)' "$ETH_FROM" | sed 's/^0*//')" == 1 ]]; then
            seth send "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$MCD_SPOT"
            seth send "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$MCD_END"
        fi
    fi
done

log "SET ILKS PIP WHITELIST COMPLETED SUCCESSFULLY"
