#!/usr/bin/env bash
set -ex

export ETH_GAS=${ETH_GAS:-"7000000"}

# Get config variables
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
CONFIG_FILE="$DIR/../out/config.json"

# shellcheck source=/dev/null
. "$DIR/load-addresses"

{ test "$1" != "flap" && test "$1" != "flop"; } && exit 1

# Set ttl
ttl=$(jq -r ".$1_ttl" "$CONFIG_FILE")
if [ "$ttl" != "" ]; then
    calldata="$(seth calldata 'file(address,address,address,bytes32,uint256)' "$MCD_PAUSE" "$MCD_PAUSE_PLAN" "$(eval echo "\$MCD_$(echo "$1" | tr '[:lower:]' '[:upper:]')")" "$(seth --to-bytes32 "$(seth --from-ascii "ttl")")" "$ttl")"
    seth send "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
fi

echo "SET $(echo "$1" | tr '[:lower:]' '[:upper:]') TTL COMPLETED SUCCESSFULLY"
