#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

if [[ -z "$ETH" ]]; then
    ETH=$(dappCreate mrs-deploy WETH9_)
    log "ETH=$ETH"
    export ETH
fi

# shellcheck source=libexec/mrs/deploy-ilk
. "$LIBEXEC_DIR/mrs/deploy-ilk" "ETH" "${1:-"A"}" "GemJoin"
