#!/usr/bin/env bash

#  Copyright (C) 2019-2021 Maker Ecosystem Growth Holdings, INC.

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

type=$(jq -r ".tokens.${1} | .pipDeploy | .type" "$CONFIG_FILE")
if [[ "$type" == "value" ]]; then
    # Set DSValue price
    sethSend "$(eval echo "\$VAL_${1}")" 'poke(bytes32)' "$(seth --to-uint256 "$(seth --to-wei "$2" ETH)")"
fi

if [[ "$(eval echo "\$PIP_${1}")" != "$(eval echo "\$VAL_${1}")" ]]; then
    # Poke OSM
    sethSend "$(eval echo "\$PIP_${1}")" 'poke()'
fi
