#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

log "SET VOW DUMP:"

# Set general debt ceiling (if defined)
dump=$(jq -r ".vow_dump" "$CONFIG_FILE")
if [[ "$dump" != "" ]]; then
    dump=$(echo "$dump"*10^18 | bc)
    dump=$(seth --to-uint256 "${dump%.*}")
    calldata="$(seth calldata 'file(address,address,address,bytes32,uint256)' "$MCD_PAUSE" "$MCD_GOV_ACTIONS" "$MCD_VOW" "$(seth --to-bytes32 "$(seth --from-ascii "dump")")" "$dump")"
    sethSend "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
fi
