#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

type=$(jq -r ".tokens.${1} | .pipDeploy | .type" "$CONFIG_FILE")
if [[ "$type" == "value" ]]; then
    # Set DSValue price
    sethSend "$(eval echo "\$MEDIANIZER_${1}")" 'poke(bytes32)' "$(seth --to-uint256 "$(seth --to-wei "$2" ETH)")"
fi

if [[ "$(eval echo "\$ORACLE_SECURITY_MODULE_${1}")" != "$(eval echo "\$MEDIANIZER_${1}")" ]]; then
    # Poke OSM
    sethSend "$(eval echo "\$ORACLE_SECURITY_MODULE_${1}")" 'poke()'
fi
