#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

log "SET ILKS PIP WHITELIST:"

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    # Check if ETH_FROM is relied or $PIP_${token} doesn't have a wards system
    set +e; RELIED=$(seth call "$(eval echo "\$PIP_${token}")" 'wards(address)(uint256)' "$ETH_FROM" 2>/dev/null); set -e

    # "" : Doesn't have wards system
    # "0": Has wards system and ETH_FROM is not relied
    # "1": Has wards system and ETH_FROM is relied

    if [[ "$RELIED" == "1" ]]; then
        # Whitelist Spotter in PIP (OSM or Median)
        sethSend "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$MCD_SPOT"
        sethSend "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$MCD_END"
    fi
done
