#!/usr/bin/env bash

#  Copyright (C) 2019-2021 Maker Ecosystem Growth Holdings, INC.

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

log "SET ILKS CLIPPER-MOM:"

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    ilks=$(jq -r ".tokens.${token}.ilks | keys_unsorted[]" "$CONFIG_FILE")
    for ilk in $ilks; do
        flipDeploy="$(jq ".tokens.${token}.ilks.${ilk} | .flipDeploy!=null" "$CONFIG_FILE")"
        if [[ "$flipDeploy" == false ]]; then
            calldata="$(seth calldata 'rely(address,address,address,address)' "$MCD_PAUSE" "$MCD_GOV_ACTIONS" "$(eval echo "\$MCD_CLIP_${token}_${ilk}")" "$CLIPPER_MOM")"
            sethSend "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$PROXY_PAUSE_ACTIONS" "$calldata"
            cm_tolerance=$(jq -r ".tokens.${token}.ilks.${ilk} | .clipDeploy.cm_tolerance" "$CONFIG_FILE")
            cm_tolerance=$(echo "${cm_tolerance}*10^25" | bc -l)
            cm_tolerance=${cm_tolerance%.*}
            sethSend "$CLIPPER_MOM" 'setPriceTolerance(address,uint256)' "$(eval echo "\$MCD_CLIP_${token}_${ilk}")" "$cm_tolerance"
        fi
    done
done

sethSend "$CLIPPER_MOM" 'setAuthority(address)' "$MCD_ADM"
sethSend "$CLIPPER_MOM" 'setOwner(address)' "$MCD_PAUSE_PROXY"
