#!/usr/bin/env bash

#  Copyright (C) 2019-2021 Maker Ecosystem Growth Holdings, INC.

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

log "SET ILKS PIP WHITELIST:"

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    # Check if ETH_FROM is relied or $PIP_${token} doesn't have a wards system
    set +e; RELIED=$(seth call "$(eval echo "\$PIP_${token}")" 'wards(address)(uint256)' "$ETH_FROM" 2>/dev/null); set -e

    # "" : Doesn't have wards system
    # "0": Has wards system and ETH_FROM is not relied
    # "1": Has wards system and ETH_FROM is relied

    if [[ "$RELIED" == "1" ]]; then
        # Whitelist Spotter in PIP (OSM or Median)
        sethSend "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$MCD_SPOT"
        sethSend "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$MCD_END"
        ilks=$(jq -r ".tokens.${token}.ilks | keys_unsorted[]" "$CONFIG_FILE")
        for ilk in $ilks; do
            flipDeploy="$(jq ".tokens.${token}.ilks.${ilk} | .flipDeploy!=null" "$CONFIG_FILE")"
            if [[ "$flipDeploy" == false ]]; then
                sethSend "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$(eval echo "\$MCD_CLIP_${token}_${ilk}")"
                sethSend "$(eval echo "\$PIP_${token}")" 'kiss(address)' "$CLIPPER_MOM"
            fi
        done
    fi
done
