#!/usr/bin/env bash

#  Copyright (C) 2019-2021 Maker Ecosystem Growth Holdings, INC.

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

log "SET PIPS RIGHTS:"

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
for token in $tokens; do
    pipAddr=$(jq -r ".tokens.${token} | .import.pip | values" "$CONFIG_FILE")
    if [[ "$pipAddr" == "" ]]; then
        type=$(jq -r ".tokens.${token} | .pipDeploy | .type | values" "$CONFIG_FILE")
        if [[ "$type" == "median" ]]; then
            sethSend "$(eval echo "\$VAL_${token}")" 'rely(address)' "$MCD_PAUSE_PROXY"
            sethSend "$(eval echo "\$VAL_${token}")" 'deny(address)' "$ETH_FROM"
        fi
        if [[ "${type}" == "value" ]]; then
            sethSend "$(eval echo "\$VAL_${token}")" 'setOwner(address)' "$MCD_PAUSE_PROXY"
        fi

        osmDelay=$(jq -r ".tokens.${token} | .pipDeploy | .osmDelay" "$CONFIG_FILE")
        if [[ "$osmDelay" -gt 0 ]]; then
            sethSend "$(eval echo "\$PIP_${token}")" 'rely(address)' "$MCD_PAUSE_PROXY"
            sethSend "$(eval echo "\$PIP_${token}")" 'deny(address)' "$ETH_FROM"
        fi
    fi
done
