on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install nix 2.3.6
      uses: cachix/install-nix-action@v19
      with:
        install_url: https://releases.nixos.org/nix/nix-2.3.6/install
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Use maker cachix
      uses: cachix/cachix-action@v19
      with:
        name: maker
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Run tests
      run: nix-build -j2 | cachix push maker
